require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalesTweetsController do

  # This should return the minimal set of attributes required to create a valid
  # SalesTweet. As you add validations to SalesTweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalesTweetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sales_tweets as @sales_tweets" do
      sales_tweet = SalesTweet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sales_tweets).should eq([sales_tweet])
    end
  end

  describe "GET show" do
    it "assigns the requested sales_tweet as @sales_tweet" do
      sales_tweet = SalesTweet.create! valid_attributes
      get :show, {:id => sales_tweet.to_param}, valid_session
      assigns(:sales_tweet).should eq(sales_tweet)
    end
  end

  describe "GET new" do
    it "assigns a new sales_tweet as @sales_tweet" do
      get :new, {}, valid_session
      assigns(:sales_tweet).should be_a_new(SalesTweet)
    end
  end

  describe "GET edit" do
    it "assigns the requested sales_tweet as @sales_tweet" do
      sales_tweet = SalesTweet.create! valid_attributes
      get :edit, {:id => sales_tweet.to_param}, valid_session
      assigns(:sales_tweet).should eq(sales_tweet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SalesTweet" do
        expect {
          post :create, {:sales_tweet => valid_attributes}, valid_session
        }.to change(SalesTweet, :count).by(1)
      end

      it "assigns a newly created sales_tweet as @sales_tweet" do
        post :create, {:sales_tweet => valid_attributes}, valid_session
        assigns(:sales_tweet).should be_a(SalesTweet)
        assigns(:sales_tweet).should be_persisted
      end

      it "redirects to the created sales_tweet" do
        post :create, {:sales_tweet => valid_attributes}, valid_session
        response.should redirect_to(SalesTweet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sales_tweet as @sales_tweet" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesTweet.any_instance.stub(:save).and_return(false)
        post :create, {:sales_tweet => { "text" => "invalid value" }}, valid_session
        assigns(:sales_tweet).should be_a_new(SalesTweet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesTweet.any_instance.stub(:save).and_return(false)
        post :create, {:sales_tweet => { "text" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sales_tweet" do
        sales_tweet = SalesTweet.create! valid_attributes
        # Assuming there are no other sales_tweets in the database, this
        # specifies that the SalesTweet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SalesTweet.any_instance.should_receive(:update).with({ "text" => "MyText" })
        put :update, {:id => sales_tweet.to_param, :sales_tweet => { "text" => "MyText" }}, valid_session
      end

      it "assigns the requested sales_tweet as @sales_tweet" do
        sales_tweet = SalesTweet.create! valid_attributes
        put :update, {:id => sales_tweet.to_param, :sales_tweet => valid_attributes}, valid_session
        assigns(:sales_tweet).should eq(sales_tweet)
      end

      it "redirects to the sales_tweet" do
        sales_tweet = SalesTweet.create! valid_attributes
        put :update, {:id => sales_tweet.to_param, :sales_tweet => valid_attributes}, valid_session
        response.should redirect_to(sales_tweet)
      end
    end

    describe "with invalid params" do
      it "assigns the sales_tweet as @sales_tweet" do
        sales_tweet = SalesTweet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesTweet.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_tweet.to_param, :sales_tweet => { "text" => "invalid value" }}, valid_session
        assigns(:sales_tweet).should eq(sales_tweet)
      end

      it "re-renders the 'edit' template" do
        sales_tweet = SalesTweet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesTweet.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_tweet.to_param, :sales_tweet => { "text" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sales_tweet" do
      sales_tweet = SalesTweet.create! valid_attributes
      expect {
        delete :destroy, {:id => sales_tweet.to_param}, valid_session
      }.to change(SalesTweet, :count).by(-1)
    end

    it "redirects to the sales_tweets list" do
      sales_tweet = SalesTweet.create! valid_attributes
      delete :destroy, {:id => sales_tweet.to_param}, valid_session
      response.should redirect_to(sales_tweets_url)
    end
  end

end
